#!/bin/bash

PHPVERSION=7.2
ENVIRONMENT=production

docker build \
    --build-arg PHPVERSION=$PHPVERSION \
    --build-arg ENVIRONMENT=$ENVIRONMENT \
    --build-arg NAMESERVER=$NAMESERVER \
    --build-arg SOURCEMIRROR=$SOURCEMIRROR \
    --build-arg TIMEZONE=$TIMEZONE \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME \
    .